server:
  port: ${PORT:57added e00}
spring:
  application:
    name: notification-service
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    locations: classpath:db/migrations
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?allowPublicKeyRetrieval=true&sslMode=DISABLED
  r2dbc:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: r2dbc:mysql://${DB_HOST}/${DB_NAME}?allowPublicKeyRetrieval=true&sslMode=DISABLED
  cloud:
    function:
      definition: sendSmsConsumer
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKER:localhost:9092}
      bindings:
        sendSmsConsumer-in-0:
          destination: school_management_sms_topic
movesms:
  username: allang_4779
  sender: SMARTLINK
  api-key: ${MOVE_SMS_API_KEY}
  url: https://sms.movesms.co.ke/api/compose
