server:
  port: 5699
spring:
  application:
    name: notification-service
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    locations: classpath:db/migrations
    user: allang
    password: cnd80751xh
    url: jdbc:mysql://localhost:3307/school_management_notification?allowPublicKeyRetrieval=true&sslMode=DISABLED
  r2dbc:
    username: allang
    password: cnd80751xh
    url: r2dbc:mysql://localhost:3307/school_management_notification?allowPublicKeyRetrieval=true&sslMode=DISABLED
  cloud:
    function:
      definition: sendSmsConsumer

    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKER:localhost:9092}

      bindings:
        sendSmsConsumer-in-0:
          destination: school_management_sms_topic
movesms:
  username: allang_4779
  sender: SMARTLINK
  api-key: ${MOVE_SMS_API_KEY}
  url: https://sms.movesms.co.ke/api/compose
