version: '3.7'
services:
  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui_school
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    volumes:
      - /home/allang/kui/config.yaml:/etc/kafkaui/dynamic_config.yaml

