version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.0
    restart: always
    container_name: zookeeper_school
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.4.0
    container_name: kafka_school
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - zookeeper
  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui_school
    restart: always

    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      AUTH_TYPE: "LOGIN_FORM"
      SPRING_SECURITY_USER_NAME: allang
      SPRING_SECURITY_USER_PASSWORD: cnd80751xh
    volumes:
      - /home/allang/kui/config.yaml:/etc/kafkaui/dynamic_config.yaml
    depends_on:
      - kafka


