server:
  port: 5698
spring:
  application:
    name: auth-server
  r2dbc:
    username: allang
    password: cnd80751xh
    url: r2dbc:mysql://localhost:3307/school_management_auth?sslMode=DISABLED
  flyway:
    enabled: true
    user: allang
    password: cnd80751xh
    url: jdbc:mysql://localhost:3307/school_management_auth?sslMode=DISABLED
    validate-on-migrate: true
    locations: classpath:db/migration
logging:
  level:
    org.flywaydb.core: DEBUG
keys:
  name: keystore.p12
  password: cnd80751xh
  alias: myalias


