server:
  port: 5698
spring:
  application:
    name: auth-server
  r2dbc:
    username: allang
    password: cnd80751xh
    url: r2dbc:mysql://localhost:3307/school_management_auth?sslMode=DISABLED
  flyway:
    enabled: true
    user: allang
    password: cnd80751xh
    url: jdbc:mysql://localhost:3307/school_management_auth?allowPublicKeyRetrieval=true&useSSL=false
    validate-on-migrate: true
    locations: classpath:db/migration
  cloud:
    function:
      definition: createUserConsumer;producer
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
          min-partition-count: 2

      bindings:
        createUserConsumer-in-0:
            destination: school_management_user_creation
        producer-out-0:
            destination: school_management_sms_topic
  jackson:
   property-naming-strategy: SNAKE_CASE
logging:
  level:
    org.flywaydb.core: DEBUG
keys:
  name: keystore.p12
  password: cnd80751xh
  alias: myalias


