server:
  port: ${PORT:5700}
spring:
  application:
    name: auth-server
  r2dbc:
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    url: r2dbc:mysql://${DB_HOST:localhost:3307}/${DB_NAME}?sslMode=DISABLED
  flyway:
    enabled: true
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST:localhost:3307}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
    validate-on-migrate: true
    locations: classpath:db/migration
  cloud:
    function:
      definition: createUserConsumer;producer
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKER}
          auto-create-topics: true
          min-partition-count: 2
      bindings:
        createUserConsumer-in-0:
            destination: school_management_user_creation
        producer-out-0:
            destination: school_management_sms_topic
  jackson:
   property-naming-strategy: SNAKE_CASE
logging:
  level:
    org.flywaydb.core: DEBUG
keys:
  name: keystore.p12
  password: ${KEYSTORE_PASSWORD:cnd80751xh}
  alias: myalias


