server:
  port: 5700
spring:
  application:
    name: user-service
  flyway:
    password: ${DB_PASSWORD:cnd80751xh}
    user: ${DB_USER:allang}
    url: jdbc:mysql://${DB_HOST:localhost:3307}/${DB_NAME:school_management_user}?allowPublicKeyRetrieval=true
    locations: classpath:db/migration
  r2dbc:
    username: ${DB_USER:allang}
    password: ${DB_PASSWORD:cnd80751xh}
    url: r2dbc:mysql://${DB_HOST:localhost:3307}/${DB_NAME:school_management_user}?sslMode=DISABLED
  jackson:
    property-naming-strategy: SNAKE_CASE
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKER:localhost:9092}

          auto-create-topics: true



