server:
  port: 5700
spring:
  application:
    name: user-service
  flyway:
    password: ${DB_PASSWORD}
    user: ${DB_USER}
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?allowPublicKeyRetrieval=true
    locations: classpath:db/migration
  r2dbc:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: r2dbc:mysql://${DB_HOST}/${DB_NAME}?sslMode=DISABLED
  jackson:
    property-naming-strategy: SNAKE_CASE
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKER:localhost:9092}
      bindings:
       createUserProducer-out-0:
          destination: school_management_user_creation


