name: auth-server-deployment
on:
  push:
    branches: [master]
    paths:
      - "auth-server/**"
      - ".github/workflows/auth-server.yaml"
jobs:
  build-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build base image
        run: |        
            cd auth-server
            docker build -t dockerallang/school-management-server:latest .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push base image
        run:
          docker push ${{ secrets.DOCKER_USERNAME }}/school-management-server:latest

