name: auth-server-deployment
on:
  push:
    branches: [master]
    paths:
      - "auth-server/**"
jobs:
  build-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build base image
        run: docker build -t auth-server-builder -f builder.Dockerfile .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push base image
        run:
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-server-builder:latest
  build-and-push-image:
      runs-on: ubuntu-latest      
      needs: build-base-image
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Build and push image
          run: |
            docker build -t auth-server .
            docker tag auth-server ${{ secrets.DOCKER_USERNAME }}/auth-server
            docker push ${{ secrets.DOCKER_USERNAME }}/auth-server
