name: Core User Service Deployment
on:
  push:
    branches: [ master ]
    paths:
      - "student-management-gateway/**"
      - ".github/workflows/gateway-service.yaml"
jobs:
  build-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build base image
        run: |
          cd core-user-service
          docker build -t dockerallang/school-management-gateway-service:latest .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push base image
        run:
          docker push ${{ secrets.DOCKER_USERNAME }}/school-management-gateway-service:latest

