name: Parent module deployment
on:
  push:
    branches: [master]
    paths:
      - "../../pom.xml"
      - "./parent-module/**"
jobs:
   build-parent-image:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Parent Images
        run: |
          docker build -t school-manager-parent:latest -f parent.Dockerfile .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push base image
        run:
            docker push ${{ secrets.DOCKER_USERNAME }}/school-manager-parent:latest
